# Default profile configuration
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: jira-clone
  profiles:
    include: secret


  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/jiraclone
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging configuration
logging:
  level:
    root: INFO
    com.btronics.jiraclone: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Development profile
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG

# Test profile
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/jiraclone_test
  jpa:
    show-sql: true

# Production profile
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false

logging:
  level:
    root: WARN
    com.btronics.jiraclone: INFO
    org.hibernate.SQL: WARN