name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Please provide detailed information about the bug.
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: Describe the bug in detail
    validations:
      required: true

  - type: dropdown
    id: sprint
    attributes:
      label: Sprint
      description: Which sprint should this bug be fixed in?
      options:
        - Sprint 1
        - Sprint 2
        - Sprint 3
        - Backlog
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - 🔴 High
        - 🟡 Medium
        - 🟢 Low
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      options:
        - "1"
        - "2"
        - "3"
        - "5"
        - "8"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe what should happen
    validations:
      required: true