name: User Story
description: Create a new user story
title: "[Story]: "
labels: ["story"]
body:
  - type: markdown
    attributes:
      value: |
        ## Create a new user story
        Please fill out the information below to create a well-defined user story.
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: As a [user type], I want to [action] so that [benefit]
      placeholder: As a registered user, I want to login with my credentials so that I can access my account
    validations:
      required: true

  - type: dropdown
    id: sprint
    attributes:
      label: Sprint
      description: Which sprint is this story planned for?
      options:
        - Sprint 1
        - Sprint 2
        - Sprint 3
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - 🔴 High
        - 🟡 Medium
        - 🟢 Low
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Effort (Story Points)
      options:
        - "1"
        - "2"
        - "3"
        - "5"
        - "8"
        - "13"
    validations:
      required: true

  - type: dropdown
    id: epic
    attributes:
      label: Epic
      options:
        - 🏗️ Infrastructure
        - 👤 User Management
        - 📋 Project Management
        - 🎫 Issue Management
        - 📄 Documentation 
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the conditions that must be met for this story to be completed
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Implementation Tasks
      description: Break down the implementation into specific tasks
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3
    validations:
      required: true

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any technical considerations or implementation details
      placeholder: |
        - Dependencies required
        - Technical constraints
        - Design considerations
    validations:
      required: false
